### ISSUE TITLE
Wasn't the plugin designed to also support PHP 5.6?

### ISSUE THREAD

**Issue by fr0z3nfyr** [filebase/Filebase#17]
I'm not sure if you wrote the plugin to work with 5.6 or not. I installed it using composer but it never complained, so it's obvious that you didn't add this dependency of `php 7.0`.

I did notice in #15 that you developed this plugin originally on `php7` but I'd expect it to work on `>= PHP5.6` as well (I have 5.6.25). I see that you have used several features of PHP that re not supported below `7.0`. For example, `spaceship` operators in `src\QueryLogic.php` on line `L210, L213`.

Any possibility of supporting `php 5.x` fully?

**Comment by timothymarois** [comment]
@fr0z3nfyr Good point. I mostly built it using PHP 7. But the idea was to support older PHP versions. I will address this in the next update, and add this to the phpunit tests.

**Comment by fr0z3nfyr** [comment]
Thanks for the response. Glad to hear that. 

Any timeline plans? I might want to look into this if you feel this may take a long time (I understand it gets very difficult to find some spare time sometimes).

**Comment by timothymarois** [comment]
@fr0z3nfyr If you think you could run some tests on php 5.6 and switch around a few of the syntax components that it doesn't like, I'd say go for it, and send in your pull request. I wouldn't be able to get to it anytime soon since I have a few other projects on the to-do list. There isn't too much code to look through, so I'd imagine it would be pretty simple to fix.

**Comment by fr0z3nfyr** [comment]
I'll see if I can start on it over this weekend. Will send a PR if I happen to fix it for 5.6 (at least). 

Cheers!

**Comment by fr0z3nfyr** [comment]
Hi. Sorry couldn't share enough time this past weekend. Will try to finish this week.

**Comment by timothymarois** [comment]
@fr0z3nfyr No worries. Do appreciate it though. Let me know if you have any other revisions/enhancements you think we should make when you get in the code.

**Comment by timothymarois** [comment]
Updated to v1.0.18 which has php 5.6 fixes. I hope that resolves any issues you have.
