### ISSUE TITLE
[FEATURE REQUEST] Secure .json files against snooping...

### ISSUE THREAD

**Issue by d8ahazard** [filebase/Filebase#32]
While I know this responsibility should *really* fall on the owner of the webserver - I've distributed a few different PHP web applications that are intended to be used by your average "anyman" as much as can be expected for a PHP web app.

As such, I've adopted the habit of "protecting" data files using a simple trick...

I append .php to the filename, and then insert the following string at the top of the file:

`'; <?php die('Access denied'); ?>`

It's super-simple, and a guaranteed way to prevent data leakage in the event that the directory used to store the .json files isn't protected against directory enumeration.

Thoughts?

**Comment by timothymarois** [comment]
Hi @d8ahazard,

That's a good security concern. I know Apache can block the directory listings from the public, but we know most people have no access or no idea to do that. 

The other thing I would add is, the **database path should never be in public view** for this exact reason. It's best practice to store this in some `/storage` directory above the HTTP `public` directory.

If you used file names more like hashes, then people trying to guess the file names would be nearly impossible, but if the directory itself is being accessed as the root, an easier solution than the conversion of php files is using `index.html` inside the root of each database path. 

Not sure I see this being a Filebase feature, unless we added the index.html automatically to the root of each database path, (an optional feature in the db config variable)

**Comment by d8ahazard** [comment]
Hey @timothymarois, thanks for the quick reply.

Haha...I feel so dumb right now. I did not even know that was an option!!

Yeah, I enjoy the KISS approach, I'll just add the blank index.html files as needed. (In fact, I've got blank _placeholder files for git already, I can just rename those.

Thanks for the tip!!
