### ISSUE TITLE
Feature Request: $item->fromArray

### ISSUE THREAD

**Issue by landall** [filebase/Filebase#37]
Though there is a method of $item named toArray, I think load data from an array is also needed.
$item = $db->get($key);
$item->fromArray($some_array);
$item->save();

**Comment by landall** [comment]
Maybe can be implemented by save($array) and load again.

**Comment by timothymarois** [comment]
That is correct, you can replace all content in the document using the `save()` method. 
```
$document->save([
    'title' => 'My Document'
]);
```
