### ISSUE TITLE
results() returns document instead of array

### ISSUE THREAD

**Issue by AdriaandeJongh** [filebase/Filebase#41]
The following query returns a single Document instead of an array if there is only 1 document that matches the query:

```
$result = $bd->query()->select('var1')->where('var2','!=','')->results();
```

The docs state results() should always just return an array, so this was a hard catch ;)

**Comment by timothymarois** [comment]
@AdriaandeJongh Thanks! I will add that to the tests and see what's going on there. If I find it, I'll add a patch in the next fix. Maybe, for now, run a check to see if its a document or an array.

**Comment by aalfiann** [comment]
I've had same problem.

The first result is array (no problem), but the next result is not array but Document object.

**Comment by timothymarois** [comment]
@aalfiann Can you confirm this is an issue when cache is set to true?

Does it work on the first query, and then the second query (cached) does not? Which would mean its related to reading the cache.

**Comment by aalfiann** [comment]
No, the cache is fine, It seems there is a problem in run() function.

 I'm not sure, but for temporary right now, I just disabled cache when use select(array) and everything is ok.

**Comment by timothymarois** [comment]
@aalfiann Ok, thanks for confirming. I will look into this and see if there is a patch to be made.

**Comment by timothymarois** [comment]
@AdriaandeJongh This has been resolved from a recent by fix by @faryar76 – Thanks again!
