### ISSUE TITLE
Feature request: sort by update or create time

### ISSUE THREAD

**Issue by AdriaandeJongh** [filebase/Filebase#42]
There doesn't seem to be a way to sort results by update or create time. This is useful for queries where I'd like to get the most recent changed files.

**Comment by aalfiann** [comment]
There is little bit tricky for this : 

```
require_once ('vendor/autoload.php');
use \Filebase\Database;

$database = new Database([
    'dir' => 'storage/user',
    'backupLocation' => 'storage/backup'
]);

// Get all data
$list = $database->findAll();

// Create new array sort the list
foreach ($list as $key => $item) {
    $resort[$key] = $item->createdAt();
}
// Re-sorting list
array_multisort($resort, SORT_DESC, $list);

// Echo the sorted list
foreach($list as $key => $item) {
    echo $key.'. '.$table->getId().' | '.$table->createdAt().' | '.$table->updatedAt().'<br>';
}
```

Note:
- I know this is not efficient.
- Set limit, make sure don't loop all data.

**Comment by timothymarois** [comment]
This has been added in the latest update. I've added it to the readme within [querying](https://github.com/filebase/Filebase#8-queries)
