### ISSUE TITLE
Case Insensitive Equals Operator

### ISSUE THREAD

**Issue by jrondorf** [filebase/Filebase#53]
Regarding https://github.com/filebase/Filebase#8-queries and the '=' operator:

Is there a way to have a case-insensitive equals operation?

(LIKE is already case-insensitive)?

Should we / I add something like EQUALS_IGNORE_CASE?

Cheers!

**Comment by faryar76** [comment]
i think you can use 
== or ===
instead of '=' for case-insensitive

**Comment by jrondorf** [comment]
@faryar76  No, also with '==' or '===' **no** case insensitive comparison will be done.

**Comment by faryar76** [comment]
> @faryar76 No, also with '==' or '===' **no** case insensitive comparison will be done.

you can use regex
where('name','regex','/john/i')

**Comment by jrondorf** [comment]
@faryar76 Thanks, the regex option works for me.
