### ISSUE TITLE
how to start using this library no tutorial ?

### ISSUE THREAD

**Issue by bcs02123052** [filebase/Filebase#54]
how to use this library there is no  getting started or any examples folder . please add some example to show how to create database and the document and not override them ?

**Comment by timothymarois** [comment]
Hello,

You should be able to find the majority of the usage on the **[readme](https://github.com/filebase/Filebase/blob/1.0/README.md).** 

Here are the [examples and usage
](**url**).
You don't necessarily create the database, but you define it using (directory is automatically created if not exist).

```php
$database = new \Filebase\Database([
    'dir' => 'path/to/database/dir'
]);
```

and then you can create specific documents and store your data like this: (documents are created automatically if not exist) 

```php
$item = $database->get('myitem');
```

Hope this helps.
