### ISSUE TITLE
How to save more than one data inside a document?

### ISSUE THREAD

**Issue by praneetroopra** [filebase/Filebase#58]
I am using your package in laravel , i have a form which allows user to add categories. But when i do that every time user submits a new category it replaces the old category , is there any way to not let it over write?

Here is my code

```
 public function store(Request $request)

    {
        $user = Auth::user()->business->name;
        $id = Auth::user()->id;
        $dir = $user.'00'.$id;
        $database = new Database([
            'dir' => $dir
        ]);
        $item = $database->get('category');
        $item->name = $request->name;
        $item->save();
        return dd($item);
    }
```
Please any help will be appreciated.

**Comment by timothymarois** [comment]
Hi @praneetroopra 

If I understand what you're trying to do, you should add these categories into an array within your document. 

Like, isnt of creating a `name` property, create a `list` = `Array`. So you can do `list = ['category', category 2']` etc. 

There are other ways to accomplish this, if you have more data within a category, you could create a new document naming it by category and then add more information inside there as well. All depends on what you're trying to accomplish.

Given this isn't a bug report, I'm going to close this ticket.
